trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '13.x'
    displayName: 'Install Node.js'

  - script: |
      cd backend_functions
      npm install -g azure-functions-core-tools@3
      npm install
      npm run build
    displayName: 'Build backend_functions project'

  - script: |
      cd backend_worker
      npm install -g azure-functions-core-tools@3
      npm install
      npm run build
    displayName: 'Build backend_worker project'

  - script: |
      cd frontend
      npm install -g @angular/cli
      npm install
      ng lint
      npm run prerender
    displayName: 'Build frontend project'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/s'
      Contents: '**/.artifactignore'
      TargetFolder: '$(Pipeline.Workspace)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'build'
      publishLocation: 'pipeline'
